### ISSUE TITLE
Old Onemix3s with i7-8500y+hd615

### ISSUE THREAD

**Issue by snazzybunny** [lulujyc/OneMix3Pro-OpenCore#1]
Hi,

How does it work for you? Are you using it every day? It probably won't work for my old onemix3s so I might need to upgrade it to the new one. Thanks for the advice!

**Comment by lulujyc** [comment]
Hello,

One Mix 3s with 8th gen core is NOT supported due to different ACPI tables and I definitely suggest avoiding trying it because the BIOS for the two platforms are different meaning that using my patched SSDTs might cause potential harm to your hardware.

If you are able to grab any One Mix 3 with a 10th gen CPU then you're good and it should be compatible by then.

**Comment by snazzybunny** [comment]
Thanks for the help! The pen works as well? Should the onemix 4 also work in theory? Take care and thanks again.

**Comment by lulujyc** [comment]
> Thanks for the help! The pen works as well? Should the onemix 4 also work in theory? Take care and thanks again.

I have no pen to test but it should work in theory. onemix 4 will probably never work as Apple gives up 11th gen support

**Comment by snazzybunny** [comment]
Thanks so much for your efforts. I'll see if I can find one and try it :).

**Comment by lulujyc** [comment]
> 
> 
> Thanks so much for your efforts. I'll see if I can find one and try it :).

You're welcome :)

**Comment by snazzybunny** [comment]
Did you end up getting rid of your onemix 3? Was it not good enough for hackintosh?
